### PR TITLE
Added a Dockerfile and README for building and running OpenWPM on Docker

### PR DESCRIPTION
**Pull request by hadiasghari**

### CODE REVIEW

**Comment by motin** [comment]
Tested and can confirm it works, thanks :)

However, this PR adds a Dockerfile in a separate directory, which in turns builds Docker images by cloning the OpenWPM repository (https://github.com/citp/OpenWPM/pull/150/files#diff-ebacf6f6ae4ee68078bb16454b23247dR35).

I suggest that you upload the files in this PR to a separate repository called docker-openwpm or similar. Or, you could refactor this PR to add a Dockerfile to that uses the already cloned repository repository.

**Comment by hadiasghari** [comment]
This is a good point, @motin. Note that the second git clone is done inside the docker container, and in any case the sources need to be copied from the host or an external source to inside the container. I however see your point, as using the already cloned code would make it easier to experiment with code changes. Let me have a look at this.

**Comment by englehardt** [comment]
Thanks for testing @motin :).

@hadiasghari I'll wait to hear back from you before merging.

**Comment by hadiasghari** [comment]
@motin @englehardt changed the Dockerfile to use the already cloned source, and accordingly updated the instructions.

**Comment by hadiasghari** [comment]
I noticed OpenWPM just updated to FF 52, the Dockerfile will also need an update.

**Comment by hadiasghari** [comment]
Sorry will do a new updated pull request, closing this one for now.

**Pull request closed without merging**
