### PR TITLE
Use extension based http request and responses for building cookie tables

### PR DESCRIPTION
**Pull request by gunesacar**
Fall back to proxy based tables if extension based http_requests
or http_responses does not exist.

### CODE REVIEW

**Comment by englehardt** [comment]
Thanks!

The proxy-based instrumentation was removed entirely in https://github.com/citp/OpenWPM/pull/152, and we have no plans to add it back in. Would you mind to remove the fallback?

**Comment by gunesacar** [comment]
I thought people might still want to use this code to build cookie tables for the past crawl data.
But, maybe they should checkout a past release in order to do that, so that the code stays clean?

Let me know and I'll remove the fallback.

**Comment by englehardt** [comment]
> I thought people might still want to use this code to build cookie tables for the past crawl data.
But, maybe they should checkout a past release in order to do that, so that the code stays clean?

My preference is cleaner code, as we've made other breaking changes related to this in the past. For example, the proxy tables used to be labeled `http_requests` and `http_responses` before having the `_proxy` suffix added.

**Comment by gunesacar** [comment]
It makes sense. I removed the fall back, but kept the explicit check for empty query results, just in case.

**Pull request merged**
