### PR TITLE
Added a colume with the current url.

### PR DESCRIPTION
**Pull request by eriktews**
This adds a colume named top\_url with the current URL in the address bar to the extension instrumentation to close issue #77 on github. In detail, this has been added for the http requests and reponses, javascript and cookie events.

### CODE REVIEW

**Comment by englehardt** [comment]
What motivated you to close this PR? Was it the inactivity? (if so, I apologize!)

I have been meaning to compare the values returned by your approach with some alternative sources of this info. We already have the URL of the tab for http requests via `top_level_url`. I was planning to use `worker.url` and `worker.tab.url` in `pageMod` portion of the javascript instrumentation. I wasn't sure what to use for the cookie instrument.

Does using `tabs.activeTab` ever result in an incorrect URL?

**Comment by eriktews** [comment]
Sorry, this closing was by accident.

I will go through the patch again, but I think I had problems when a redirect of some kind (http, javascript...) was encountered.

**Comment by eriktews** [comment]
Also I rebased the patch so that is is easier to merge now.

**Comment by englehardt** [comment]
Closing this since we already have the information for http requests and JS, and will now be moving to web extensions.

**Pull request closed without merging**
